### ISSUE TITLE
Not found dist

### ISSUE THREAD

**Issue by batFormat** [dooboolab/prisma-offset-pagination#3]
Error: Cannot find module '/Users/<username>/<project>/node_modules/prisma-offset-pagination/dist/index.js'. Please verify that the package.json has a valid "main" entry

**Comment by hyochan** [comment]
@0916dhkim Could you follow this issue?

**Comment by 0916dhkim** [comment]
I will look into this issue

**Comment by 0916dhkim** [comment]
@hyochan I opened a PR to address this issue.
